"""Verify and refine a generated moment: review for errors, fix issues, improve quality."""

from __future__ import annotations

from pathlib import Path

from agent.agent import Agent
from agent.tools.read import ReadTool
from agent.tools.write import WriteTool
from agent.tools.edit import EditTool
from agent.tools.terminal import TerminalTool


REFINE_SYSTEM_PROMPT = """\
You are a code review and repair agent. You review generated web apps (HTML/CSS/JS using React \
via React.createElement) for correctness and quality, then fix any issues you find.

You can read files, edit files, write files, and run shell commands. You also have web search \
to look up documentation or solutions.
"""

REFINE_USER_TEMPLATE = """\
Review and fix the web app at `{output_dir}/`. It was generated by an AI agent and may have \
errors or quality issues.

## Files to review

- `{output_dir}/index.html` — entry point, loads CSS and JS
- `{output_dir}/app.js` — main application logic with DATA object at top
- `{output_dir}/styles.css` — app-specific styles
- `{output_dir}/data.js` — data file (may not exist if data is in app.js)
- `{output_dir}/components.js` — shared React component library (DO NOT modify)
- `{output_dir}/base.css` — shared design system (DO NOT modify)
- `{output_dir}/meta.json` — metadata

## Review steps

1. **Read all files** in `{output_dir}/` to understand the app.
2. **Run `node --check`** on every `.js` file to catch syntax errors. Fix any you find.
3. **Check functional correctness:**
   - Does the JS rendering logic match the actual DATA shape? (e.g., accessing `item.title` when \
the data uses `item.name`)
   - Are there undefined variable references or wrong property paths?
   - Do event handlers and state management work correctly?
   - Does the HTML correctly load all required JS and CSS files?
4. **Check global scope rules:** `components.js` declares globals (`h`, `useState`, `useCallback`, \
`useMemo`, `useEffect`, plus component functions like `PageHeader`, `GlassCard`, `Badge`, etc.). \
`app.js` MUST NOT redeclare any of these with `const`, `let`, or `var` — remove any such \
redeclarations.
5. **Improve quality:**
   - Handle edge cases (empty data, long text, missing fields)
   - Fix layout issues (overflow, alignment, spacing)
   - Ensure interactive elements work (filters, search, tabs, sorting)
6. **After all fixes**, run `node --check` again on any files you changed to verify your fixes.

## Decision

If the app is fundamentally broken beyond repair (completely wrong data, nonsensical interface, \
core structure unsalvageable), delete `{output_dir}/index.html` to signal that this moment \
should be discarded. Only do this as a last resort — prefer fixing over deleting.

## Rules

- DO NOT modify `components.js` or `base.css` — these are shared resources.
- Use `edit_file` for surgical fixes, not full file rewrites.
- Preserve the existing design, data, and content — fix technical issues and improve quality.
"""


def verify_and_refine(
    output_dir: str,
    logs_dir: str,
    model: str,
    api_key: str | None = None,
) -> bool:
    """Review a generated moment for errors and quality, fix issues.

    Returns True if index.html still exists after review (kept or improved).
    Returns False if the agent deleted it (quality too low).
    """
    output_path = Path(output_dir)
    if not (output_path / "index.html").exists():
        return False

    print(f"  [verify] reviewing {output_dir}")

    tools = [ReadTool(), WriteTool(), EditTool(), TerminalTool()]
    agent = Agent(
        model=model,
        system_prompt=REFINE_SYSTEM_PROMPT,
        tools=tools,
        max_rounds=30,
        web_search=True,
        api_key=api_key,
    )

    message = REFINE_USER_TEMPLATE.format(output_dir=output_dir)
    agent.run([{"role": "user", "content": message}])

    exists = (output_path / "index.html").exists()
    print(f"  [verify] done — {'kept' if exists else 'deleted'}")
    return exists
